In [4]:
import numpy as np 
x = np.array([1,2,3])
print(x)
x_exp = np.exp(x)
print(x_exp)
y = 1
print(np.exp(y))

def sigmoid(z):

    g = 1 / (1+np.exp(-z))
    return g 
z_tmp = np.arange(-10,11)
y = sigmoid(z_tmp)
np.set_printoptions(precision = 3)
print(np.c_[z_tmp , y ])


[1 2 3]
[ 2.718  7.389 20.086]
2.718281828459045
[[-1.000e+01  4.540e-05]
 [-9.000e+00  1.234e-04]
 [-8.000e+00  3.354e-04]
 [-7.000e+00  9.111e-04]
 [-6.000e+00  2.473e-03]
 [-5.000e+00  6.693e-03]
 [-4.000e+00  1.799e-02]
 [-3.000e+00  4.743e-02]
 [-2.000e+00  1.192e-01]
 [-1.000e+00  2.689e-01]
 [ 0.000e+00  5.000e-01]
 [ 1.000e+00  7.311e-01]
 [ 2.000e+00  8.808e-01]
 [ 3.000e+00  9.526e-01]
 [ 4.000e+00  9.820e-01]
 [ 5.000e+00  9.933e-01]
 [ 6.000e+00  9.975e-01]
 [ 7.000e+00  9.991e-01]
 [ 8.000e+00  9.997e-01]
 [ 9.000e+00  9.999e-01]
 [ 1.000e+01  1.000e+00]]
